- name: Get cmdline.txt content
  ansible.builtin.command:
    cmd: cat /boot/firmware/cmdline.txt
  changed_when: false
  register: cmdline_content

- name: Define Linux kernal command line
  ansible.builtin.template:
    src: cmdline.txt.j2
    dest: /boot/firmware/cmdline.txt
    owner: root
    group: root
    mode: "0755"
  notify: Restart system

- name: Force all notified handlers to run at this point
  ansible.builtin.meta: flush_handlers
