- name: Prepare
  hosts: all
  tasks:
    - name: Ensure /boot/firmware directory exists
      ansible.builtin.file:
        path: /boot/firmware
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Create cmdline.txt
      ansible.builtin.copy:
        dest: /boot/firmware/cmdline.txt
        content: "console=serial0,115200 console=tty1 root=PARTUUID=ebbeb7e0-01 rootfstype=ext4 fsck.repair=yes rootwait"
